version: '3.10'

services:
  web:
    build: .
    environment:
      DB_URL: jdbc:postgresql://db:5432/mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"